# -*- coding: utf-8 -*-
"""영어단어_프로그램

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xsvL0Cl5eeguX_wCYWiF7iwqmijdk2HQ
"""

def run_word_quiz():
    """딕셔너리를 활용한 영어 단어 맞추기 퀴즈"""
    word_dict = {
        "apple": "사과",
        "banana": "바나나",
        "computer": "컴퓨터",
        "python": "파이썬",
        "opensource": "오픈소스",
    }

    print("\n--- [1] 영어 단어 퀴즈 시작 ---")
    score = 0

    for word, meaning in word_dict.items():
        user_input = input(f"'{word}'의 뜻은 무엇일까요?: ").strip()
        if user_input == meaning:
            print("정답입니다! 🎉")
            score += 1
        else:
            print(f"틀렸습니다. 정답은 '{meaning}'입니다. 😢")

    print(f"\n퀴즈 종료! 맞춘 개수: {score} / {len(word_dict)}")
run_word_quiz()